### ISSUE TITLE
sudo make failed after pull?

### ISSUE THREAD

**Issue by andyyuan78** [dato-code/PowerGraph#179]
ted/zookeeper.jute.h '/home/ubgpu/github/Dato_data/PowerGraph/deps/local/include/zookeeper'
[ 27%] Completed 'zookeeper'
[ 27%] Built target zookeeper
Scanning dependencies of target graphlab
[ 28%] Building CXX object src/graphlab/CMakeFiles/graphlab.dir/options/command_line_options.cpp.o
In file included from /home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/command_line_options.cpp:67:0:
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:3:1: warning: missing terminating " character [enabled by default]
 "ingress: The graph partitioning method to use. May be \"random\”,\n”
 ^
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:3:1: error: missing terminating " character
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
 “\”grid\”, \”pds\”, \”oblivious\” or \”hdrf\”. The methods are in”
 ^
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\234’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\342’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\200’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:1: error: stray ‘\235’ in program
/home/ubgpu/github/Dato_data/PowerGraph/src/graphlab/options/graph_help.txt:4:8: error: expected ‘,’ or ‘;’ before ‘grid’
 “\”grid\”, \”pds\”, \”oblivious\” or \”hdrf\”. The methods are in”
        ^
make[2]: *** [src/graphlab/CMakeFiles/graphlab.dir/options/command_line_options.cpp.o] Error 1
make[1]: *** [src/graphlab/CMakeFiles/graphlab.dir/all] Error 2
make: *** [all] Error 2
ubgpu@ubgpu:~/github/Dato_data/PowerGraph/debug$

**Comment by dbickson** [comment]
Hi Andy
I just submitted a fix - we had a user contribution with non ascii chars in this file.
Please note that PowerGraph project is deprecated and we recently released a newer version called Dato Core. Take a look at http://dato.com

**Comment by andyyuan78** [comment]
so what about graphlab, does it deprecated too?

**Comment by dbickson** [comment]
Not at all, our latest version is called GraphLab Create.

**Comment by andyyuan78** [comment]
Is 'GraphLab Create'  open source ?

**Comment by dbickson** [comment]
Hi Andy
Please ask all those questions in our user forum: http://forum.dato.com -
we promise to answer quickly.

Best,
