### ISSUE TITLE
Errors in running ./configure

### ISSUE THREAD

**Issue by somesh112** [dato-code/PowerGraph#180]
I am trying installing 'graphlab' on 32-bit Ubuntu 14.04.   
I installed all the dependencies and then ran ./configure. I am getting the following error.. "__builtin_ia32_crc32di’ was not declared in this scope".
How to fix this error. 

Thanks.

**Comment by dbickson** [comment]
We do not support 32 bit systems. Please post further questions here: http://forum.dato.com
