### ISSUE TITLE
Has anyone implemented DBSCAN on powergraph? 

### ISSUE THREAD

**Issue by kccai** [dato-code/PowerGraph#185]
I am having trouble with the distance matrix in DBSCAN. The distance matrix could be very large and can not fit in the main memory. How do you solve this problem? Can anyone help?

**Comment by dbickson** [comment]
Hi 
Please repost your question at our user forum http://forum.dato.com as DBSCAN is implemented on top of GraphLab Create and not PowerGraph. See documentation here: https://dato.com/products/create/docs/graphlab.toolkits.clustering.html. At any case this repo is for code issues and not user questions. 

Thanks,
